<?php
### BLOCKCHAIN CONFIGURATION ####

$_DAEMON_IP="127.0.0.1"; // IP WHERE THE NODE IS RUNNING - In local, put 127.0.0.1, MUST BE YOUR SERVER IP if RUNNING ON SERVER SIDE.

$_DAEMON_PORT="1234"; // THE DEFAULT DAEMON PORT FOT YOUR DAEMON TO RUN ON - BY DEFAULT THIRD WILL RUN ON 1234 PORT IN TCP ONLY.

$_DAEMON_HOST=$_DAEMON_IP.":".$_DAEMON_PORT;

$_nbSecondsIdle=1200;//TIMEOUT FOR TCP CONNECTION
###
